export const FORMATS = {
  alchemy: 'Alchemy',
  arena: 'Arena',
  brawl: 'Brawl',
  commander: 'Commander',
  duel: 'Duel',
  explorer: 'Explorer',
  future: 'Future',
  gladiator: 'Gladiator',
  historic: 'Historic',
  legacy: 'Legacy',
  modern: 'Modern',
  oathbreaker: 'Oathbreaker',
  oldschool: 'Oldschool',
  pauper: 'Pauper',
  paupercommander: 'Pauper EDH',
  penny: 'Penny',
  pioneer: 'Pioneer',
  predh: 'PreDH',
  premodern: 'Premodern',
  standard: 'Standard',
  standardbrawl: 'Standard Brawl',
  timeless: 'Timeless',
  vintage: 'Vintage',
}
