import type { Set } from 'scryfall-api'

export const setsArray: Set[] = [
  {
    object: 'set',
    id: '5d293ad8-a749-4725-bd5c-c4e1db828bd0',
    code: 'ecl',
    mtgo_code: 'ecl',
    arena_code: 'ecl',
    name: 'Lorwyn Eclipsed',
    uri: 'https://api.scryfall.com/sets/5d293ad8-a749-4725-bd5c-c4e1db828bd0',
    scryfall_uri: 'https://scryfall.com/sets/ecl',
    search_uri:
      'https://api.scryfall.com/cards/search?include_extras=true&include_variations=true&order=set&q=e%3Aecl&unique=prints',
    released_at: new Date('2026-01-23'),
    set_type: 'expansion',
    card_count: 0,
    digital: false,
    nonfoil_only: true,
    foil_only: true,
    icon_svg_uri: 'https://svgs.scryfall.io/sets/default.svg?1758513600',
  },
  {
    object: 'set',
    id: 'e8aa0534-a9fc-4954-8f4e-d4b3710fc3cf',
    code: 'ftla',
    name: 'Avatar: The Last Airbender Front Cards',
    uri: 'https://api.scryfall.com/sets/e8aa0534-a9fc-4954-8f4e-d4b3710fc3cf',
    scryfall_uri: 'https://scryfall.com/sets/ftla',
    search_uri:
      'https://api.scryfall.com/cards/search?include_extras=true&include_variations=true&order=set&q=e%3Aftla&unique=prints',
    released_at: new Date('2025-11-21'),
    set_type: 'memorabilia',
    card_count: 10,
    parent_set_code: 'tla',
    digital: false,
    nonfoil_only: false,
    foil_only: false,
    icon_svg_uri: 'https://svgs.scryfall.io/sets/tla.svg?1758513600',
  },
  {
    object: 'set',
    id: '118f7e64-5caa-4cb7-99a8-184f4d3a7422',
    code: 'tla',
    mtgo_code: 'tla',
    arena_code: 'tla',
    tcgplayer_id: 24421,
    name: 'Avatar: The Last Airbender',
    uri: 'https://api.scryfall.com/sets/118f7e64-5caa-4cb7-99a8-184f4d3a7422',
    scryfall_uri: 'https://scryfall.com/sets/tla',
    search_uri:
      'https://api.scryfall.com/cards/search?include_extras=true&include_variations=true&order=set&q=e%3Atla&unique=prints',
    released_at: new Date('2025-11-21'),
    set_type: 'expansion',
    card_count: 110,
    digital: false,
    nonfoil_only: false,
    foil_only: false,
    icon_svg_uri: 'https://svgs.scryfall.io/sets/tla.svg?1758513600',
  },
]
